[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
joke_race_eclipse = "CGfVb6h6wHnAxLfMw3EnssxBEPQgdyNSQzXtWVYkx7Vn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://jokerace-eclipse-e236.mainnet.eclipse.rpcpool.com/47ac9695-3de0-4385-85d4-559ba45729f9"
wallet = "./mainnnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
