[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
joke_race_eclipse = "3MDkCnEnfCYmHNVSs5xuCDdSoGrrRAGbAZ88YtFC1SRy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://staging-rpc.dev2.eclipsenetwork.xyz"
wallet = "./a.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
